# Generated by Django 3.0.8 on 2020-07-08 11:39

from django.db import migrations, models
import server_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0003_auto_20200708_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(default=server_app.models.hash_directory_path, max_length=255, unique=True),
        ),
    ]
